[2025-07-28T12:51:15.590+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-28T12:51:17.058+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: financial_etl_dag.ingest_csv manual__2025-07-28T12:41:01.472973+00:00 [queued]>
[2025-07-28T12:51:17.127+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: financial_etl_dag.ingest_csv manual__2025-07-28T12:41:01.472973+00:00 [queued]>
[2025-07-28T12:51:17.140+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2025-07-28T12:51:17.226+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): ingest_csv> on 2025-07-28 12:41:01.472973+00:00
[2025-07-28T12:51:17.538+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'financial_etl_dag', 'ingest_csv', 'manual__2025-07-28T12:41:01.472973+00:00', '--job-id', '108', '--raw', '--subdir', 'DAGS_FOLDER/financial_etl_dag.py', '--cfg-path', '/tmp/tmpe7qhv78l']
[2025-07-28T12:51:17.590+0000] {standard_task_runner.py:91} INFO - Job 108: Subtask ingest_csv
[2025-07-28T12:51:17.590+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=669) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-28T12:51:17.617+0000] {standard_task_runner.py:63} INFO - Started process 683 to run task
[2025-07-28T12:51:18.734+0000] {task_command.py:426} INFO - Running <TaskInstance: financial_etl_dag.ingest_csv manual__2025-07-28T12:41:01.472973+00:00 [running]> on host 3fd530ef422e
[2025-07-28T12:51:19.401+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='financial_etl_dag' AIRFLOW_CTX_TASK_ID='ingest_csv' AIRFLOW_CTX_EXECUTION_DATE='2025-07-28T12:41:01.472973+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-28T12:41:01.472973+00:00'
[2025-07-28T12:51:19.416+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-28T12:51:19.593+0000] {logging_mixin.py:188} INFO - [INGEST] Reading file: /opt/***/dags/files/transactions.csv
[2025-07-28T12:51:19.599+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-28T12:51:19.605+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/financial_etl_dag.py", line 40, in ingest_csv
    df = pd.read_csv(CSV_FILE)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/files/transactions.csv'
[2025-07-28T12:51:19.758+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=financial_etl_dag, task_id=ingest_csv, execution_date=20250728T124101, start_date=20250728T125117, end_date=20250728T125119
[2025-07-28T12:51:19.818+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 108 for task ingest_csv ([Errno 2] No such file or directory: '/opt/airflow/dags/files/transactions.csv'; 683)
[2025-07-28T12:51:19.865+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-28T12:51:19.916+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-28T12:51:19.923+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
