[2025-07-28T11:04:47.804+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-28T11:04:47.836+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: financial_etl_dag.load_data manual__2025-07-28T11:04:41.581475+00:00 [queued]>
[2025-07-28T11:04:47.850+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: financial_etl_dag.load_data manual__2025-07-28T11:04:41.581475+00:00 [queued]>
[2025-07-28T11:04:47.851+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-07-28T11:04:47.867+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_data> on 2025-07-28 11:04:41.581475+00:00
[2025-07-28T11:04:47.876+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'financial_etl_dag', 'load_data', 'manual__2025-07-28T11:04:41.581475+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/financial_etl_dag.py', '--cfg-path', '/tmp/tmprjxj0s5m']
[2025-07-28T11:04:47.878+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=265) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-28T11:04:47.879+0000] {standard_task_runner.py:91} INFO - Job 91: Subtask load_data
[2025-07-28T11:04:47.880+0000] {standard_task_runner.py:63} INFO - Started process 267 to run task
[2025-07-28T11:04:47.960+0000] {task_command.py:426} INFO - Running <TaskInstance: financial_etl_dag.load_data manual__2025-07-28T11:04:41.581475+00:00 [running]> on host d6f7a7d3be45
[2025-07-28T11:04:48.150+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='financial_etl_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-28T11:04:41.581475+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-28T11:04:41.581475+00:00'
[2025-07-28T11:04:48.157+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-28T11:04:48.228+0000] {logging_mixin.py:188} INFO - [LOAD] CSV path: /opt/***/dags/data/curated_transactions.csv
[2025-07-28T11:04:48.264+0000] {base.py:84} INFO - Using connection ID '***_db' for task execution.
[2025-07-28T11:04:48.277+0000] {base.py:84} INFO - Using connection ID '***_db' for task execution.
[2025-07-28T11:04:48.286+0000] {sql.py:457} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS transactions (
        transaction_id INT,
        user_id INT,
        amount FLOAT,
        currency VARCHAR(10),
        timestamp TIMESTAMP,
        merchant VARCHAR(50),
        fraud_flag BOOLEAN
    );
    , parameters: None
[2025-07-28T11:04:48.292+0000] {logging_mixin.py:188} INFO - [LOAD] Ensured transactions table exists.
[2025-07-28T11:04:48.327+0000] {logging_mixin.py:188} INFO - [LOAD] Inserted 3 rows into 'transactions'
[2025-07-28T11:04:48.328+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-28T11:04:48.330+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-28T11:04:48.343+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=financial_etl_dag, task_id=load_data, execution_date=20250728T110441, start_date=20250728T110447, end_date=20250728T110448
[2025-07-28T11:04:48.375+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-28T11:04:48.397+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-28T11:04:48.401+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
