[2025-07-28T12:41:11.223+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-28T12:41:11.378+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: financial_etl_dag.generate_monthly_summary manual__2025-07-28T12:41:01.472973+00:00 [queued]>
[2025-07-28T12:41:11.386+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: financial_etl_dag.generate_monthly_summary manual__2025-07-28T12:41:01.472973+00:00 [queued]>
[2025-07-28T12:41:11.387+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-07-28T12:41:11.398+0000] {taskinstance.py:2327} INFO - Executing <Task(PostgresOperator): generate_monthly_summary> on 2025-07-28 12:41:01.472973+00:00
[2025-07-28T12:41:11.410+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=196) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-28T12:41:11.408+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'financial_etl_dag', 'generate_monthly_summary', 'manual__2025-07-28T12:41:01.472973+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/financial_etl_dag.py', '--cfg-path', '/tmp/tmphj9yey6h']
[2025-07-28T12:41:11.411+0000] {standard_task_runner.py:63} INFO - Started process 198 to run task
[2025-07-28T12:41:11.411+0000] {standard_task_runner.py:91} INFO - Job 99: Subtask generate_monthly_summary
[2025-07-28T12:41:11.474+0000] {task_command.py:426} INFO - Running <TaskInstance: financial_etl_dag.generate_monthly_summary manual__2025-07-28T12:41:01.472973+00:00 [running]> on host 3fd530ef422e
[2025-07-28T12:41:11.538+0000] {abstractoperator.py:725} ERROR - Exception rendering Jinja template for task 'generate_monthly_summary', field 'sql'. Template: '/opt/***/dags/sql/monthly_summary.sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 166, in render_template
    template = jinja_env.get_template(value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/dags/sql/monthly_summary.sql
[2025-07-28T12:41:11.543+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2476, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2629, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3079, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 1336, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 166, in render_template
    template = jinja_env.get_template(value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/dags/sql/monthly_summary.sql
[2025-07-28T12:41:11.558+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=financial_etl_dag, task_id=generate_monthly_summary, execution_date=20250728T124101, start_date=20250728T124111, end_date=20250728T124111
[2025-07-28T12:41:11.573+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 99 for task generate_monthly_summary (/opt/airflow/dags/sql/monthly_summary.sql; 198)
[2025-07-28T12:41:11.584+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-28T12:41:11.599+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-28T12:41:11.602+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
