[2025-07-28T17:20:15.904+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-28T17:20:15.958+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: financial_etl_pipeline.ingest_data manual__2025-07-28T17:20:13.012754+00:00 [queued]>
[2025-07-28T17:20:15.969+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: financial_etl_pipeline.ingest_data manual__2025-07-28T17:20:13.012754+00:00 [queued]>
[2025-07-28T17:20:15.970+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-07-28T17:20:16.187+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): ingest_data> on 2025-07-28 17:20:13.012754+00:00
[2025-07-28T17:20:16.204+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'financial_etl_pipeline', 'ingest_data', 'manual__2025-07-28T17:20:13.012754+00:00', '--job-id', '123', '--raw', '--subdir', 'DAGS_FOLDER/financial_etl_dag.py', '--cfg-path', '/tmp/tmppax3f4_7']
[2025-07-28T17:20:16.206+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=7039) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-28T17:20:16.207+0000] {standard_task_runner.py:91} INFO - Job 123: Subtask ingest_data
[2025-07-28T17:20:16.207+0000] {standard_task_runner.py:63} INFO - Started process 7041 to run task
[2025-07-28T17:20:16.270+0000] {task_command.py:426} INFO - Running <TaskInstance: financial_etl_pipeline.ingest_data manual__2025-07-28T17:20:13.012754+00:00 [running]> on host c9a4a3294b33
[2025-07-28T17:20:16.353+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='financial_etl_pipeline' AIRFLOW_CTX_TASK_ID='ingest_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-28T17:20:13.012754+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-28T17:20:13.012754+00:00'
[2025-07-28T17:20:16.355+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-28T17:20:16.380+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-28T17:20:16.380+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/financial_etl_dag.py", line 30, in ingest_data
    raise FileNotFoundError(f"Raw file not found at {raw_file_path}")
FileNotFoundError: Raw file not found at /opt/***/dags/data/raw/transactions.csv
[2025-07-28T17:20:16.393+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=financial_etl_pipeline, task_id=ingest_data, execution_date=20250728T172013, start_date=20250728T172015, end_date=20250728T172016
[2025-07-28T17:20:16.408+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 123 for task ingest_data (Raw file not found at /opt/***/dags/data/raw/transactions.csv; 7041)
[2025-07-28T17:20:16.421+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-28T17:20:16.437+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-28T17:20:16.441+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
