[2025-07-27T17:37:48.664+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-27T17:37:49.113+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: analytics_dag.generate_report manual__2025-07-27T17:37:46.115155+00:00 [queued]>
[2025-07-27T17:37:49.129+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: analytics_dag.generate_report manual__2025-07-27T17:37:46.115155+00:00 [queued]>
[2025-07-27T17:37:49.130+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-07-27T17:37:49.154+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): generate_report> on 2025-07-27 17:37:46.115155+00:00
[2025-07-27T17:37:49.181+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=701) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-27T17:37:49.177+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'analytics_dag', 'generate_report', 'manual__2025-07-27T17:37:46.115155+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/data/analytics_dag.py', '--cfg-path', '/tmp/tmp45toj7ze']
[2025-07-27T17:37:49.183+0000] {standard_task_runner.py:63} INFO - Started process 703 to run task
[2025-07-27T17:37:49.183+0000] {standard_task_runner.py:91} INFO - Job 80: Subtask generate_report
[2025-07-27T17:37:49.319+0000] {task_command.py:426} INFO - Running <TaskInstance: analytics_dag.generate_report manual__2025-07-27T17:37:46.115155+00:00 [running]> on host d6f7a7d3be45
[2025-07-27T17:37:49.468+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='analytics_dag' AIRFLOW_CTX_TASK_ID='generate_report' AIRFLOW_CTX_EXECUTION_DATE='2025-07-27T17:37:46.115155+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-27T17:37:46.115155+00:00'
[2025-07-27T17:37:49.471+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-27T17:37:49.519+0000] {base.py:84} INFO - Using connection ID '***_db' for task execution.
[2025-07-27T17:37:49.558+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/providers/common/sql/hooks/sql.py:227 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-07-27T17:37:49.631+0000] {logging_mixin.py:188} INFO - [ANALYTICS] Report saved at: /opt/***/dags/reports/fraud_report.csv
[2025-07-27T17:37:49.633+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-27T17:37:49.634+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-27T17:37:49.644+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=analytics_dag, task_id=generate_report, execution_date=20250727T173746, start_date=20250727T173749, end_date=20250727T173749
[2025-07-27T17:37:49.688+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-27T17:37:49.709+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-27T17:37:49.712+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
